version: "3.0"

# Services to run
services:
  mongo_login: # name of BD service
    image: mongo
    container_name: mongo_db_login
    ports:
      - 27017:27017
    volumes:
      - mongologin:/data/configdb
      - mongologin:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongologin:
